import Head from "next/head"
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Showcase from "../components/Showcase"
import {useRouter} from "next/router"

export default function Layout({ title, children }) {
    const router = useRouter()
    return (
        <div>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        { router.pathname == "/" && <Showcase/>}
        { router.pathname == "/about" && <Showcase/>}
        <div className='cylinder'>
            {children}
            <style jsx>{`
                .cylinder{
                    margin: 60px auto;
                    margin-top:0;
                    max-width: 990px;
                    padding:0 30px;
                }
            `}</style>
        </div>
            
        <Footer/>
        </div>
    )
}

Layout.defaultProps = {
    title: "Event"
}